In [1]:
from flask import Flask, request,render_template,jsonify
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen

In [2]:
url = "https://www.espncricinfo.com/"

In [3]:
response_website = urlopen(url)

In [4]:
not_readable_data = response_website.read()

In [ ]:
not_readable_data

In [6]:
read_able = bs(not_readable_data, "html.parser")

In [ ]:
read_able

In [8]:
to_stats = read_able.find_all("div", {"class": "ds-popper-wrapper"})[6].a["href"]

In [9]:
to_stats

'https://www.espncricinfo.com/records'

In [10]:
to_stats1 = bs(to_stats, "html.parser")

C:\Users\solat\AppData\Local\Temp\ipykernel_14480\570860472.py:1: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  to_stats1 = bs(to_stats, "html.parser")

In [11]:
# to_stats1.find_all("div", {"class":"ds-flex ds-text-title-xs ds-items-center"})

In [12]:
# here we are getting data from the link with which we can fetch or extract data
# using find_all and providing tag and class name
product = requests.get(to_stats1)
product.encoding  = 'utf-8'

In [48]:
# parsing
to_in = bs(product.text, "html.parser")

In [ ]:
to_in

In [15]:
icc = to_in.find_all("a", {"class":"ds-px-3 ds-py-2 hover:ds-text-typo-primary"})[5]["href"]

In [16]:
t20_WC = url + icc

In [17]:
t_20 = bs(t20_WC, "html.parser")
t_20

C:\Users\solat\AppData\Local\Temp\ipykernel_14480\3009944469.py:1: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  t_20 = bs(t20_WC, "html.parser")

https://www.espncricinfo.com//records/trophy/icc-men-s-t20-world-cup-89

In [18]:
# same here we are trying to get data of the link
new_link = requests.get(t_20)
new_link.encoding = 'utf-8'

In [ ]:
new_link1 = bs(new_link.text, "html.parser")
new_link1

In [ ]:
list_of_mtc_rslt = new_link1.find_all("li", {"class": "ds-w-full ds-flex"})
list_of_mtc_rslt

In [21]:
a1= new_link1.find_all("a", {"class": "ds-cursor-pointer ds-inline-flex ds-items-center ds-w-full ds-py-2 ds-text-tight-s ds-px-4 ds-bg-ui-fill ds-text-typo ds-flex ds-items-center ds-box-border hover:ds-bg-ui-fill-hover focus:ds-border focus:ds-border-ui-stroke-primary focus:ds-outline-none"})
list_of_mtc_rslt1 = a1[1]["href"]
list_of_mtc_rslt1

'/records/trophy/team-match-results-season/icc-men-s-t20-world-cup-89'

In [22]:
to_lis_of_m_rslt = url + list_of_mtc_rslt1
to_lis_of_m_rslt

'https://www.espncricinfo.com//records/trophy/team-match-results-season/icc-men-s-t20-world-cup-89'

In [ ]:
converting_to = requests.get(to_lis_of_m_rslt)
converting_to.encoding = 'utf-8'
converting_to_data = bs(converting_to.text, "html.parser")
converting_to_data

In [ ]:
converting_to_data.find_all("div", {"class":"ds-mb-6"})

In [25]:
reached = converting_to_data.find_all("a", {"class":"ds-inline-flex ds-items-start ds-leading-none"})[7]['href']

In [26]:
to_matches = url + reached
to_matches # have to convert to pd

'https://www.espncricinfo.com//records/season/team-match-results/2022to23-2022to23?trophy=89'

In [27]:
s = pd.read_html(to_matches)
d = s[0]
df1 = pd.DataFrame(d)
df1

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,-,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
21,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
22,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
23,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
24,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
25,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
26,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
27,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
28,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
29,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
30,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
31,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
32,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
33,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
34,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
35,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
36,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
37,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
38,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
39,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
40,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
41,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [ ]:
conv_to = requests.get(to_matches)
conv_to.encoding = 'utf-8'
conv_to_data = bs(conv_to.text, "html.parser")
conv_to_data

In [ ]:
conv_to_data.find_all("span", {"class":""})

In [30]:
score_c = conv_to_data.find_all("a", {"class": "ds-inline-flex ds-items-start ds-leading-none"})[1]["href"]

In [31]:
final_score_card = url + score_c
final_score_card

'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/namibia-vs-sri-lanka-1st-match-first-round-group-a-1298135/full-scorecard'

In [32]:
import json
import csv

In [33]:
# with open("testingfile.txt", "w") as f:
#     data = csv.writer(f)
#     data.writerows(final_score_card)

In [34]:
rd = pd.read_html(final_score_card)
len(rd)
dataf1 = pd.DataFrame(rd[0])
dataf1.to_json("filejson")

In [35]:
table = conv_to_data.find_all("div", {"class": "ds-overflow-x-auto ds-scrollbar-hide"})

In [ ]:
l = []
for k in conv_to_data.find_all("td"):
    title = k.text
    l.append(title)

l

In [37]:
lst = []
headers = conv_to_data.find_all("thead", {"class": "ds-bg-fill-content-alternate ds-text-left"})[0]
for i in headers:
    title = i.text
    lst.append(title)

print(lst,end=" ")
print(len(lst))

['Team 1Team 2WinnerMarginGroundMatch DateScorecard'] 1

In [ ]:
url22 = requests.get(final_score_card)
url22.encoding = 'utf-8'
f_url = bs(url22.text, "html.parser")

f_url.find_all("thead", {"class": "ds-bg-fill-content-alternate ds-text-left"})

In [39]:
a = f_url.find_all("th", {"class":"ds-min-w-max ds-text-left ds-border-r ds-border-line"})
# m = []
# for i in a:
#     title = i.text
#     m.append(title)
a
# m

[<th class="ds-min-w-max ds-text-left ds-border-r ds-border-line">PLAYER NAME</th>,
 <th class="ds-min-w-max ds-text-left ds-border-r ds-border-line">TEAM</th>,
 <th class="ds-min-w-max ds-text-left ds-border-r ds-border-line">TEAM</th>,
 <th class="ds-min-w-max ds-text-left ds-border-r ds-border-line">TEAM</th>,
 <th class="ds-min-w-max ds-text-left ds-border-r ds-border-line">TEAM</th>]

In [40]:
score_c = conv_to_data.find_all("a", {"class": "ds-inline-flex ds-items-start ds-leading-none"})
list_of_url = []
# list of url includes urls which has ground info in it...but we dont need that
for i in range(len(score_c)):
    score = url + score_c[i]["href"]
    list_of_url.append(score)

print(len(list_of_url))
only_score_card = []
s = 1
while s <= len(list_of_url)-2:
    only_score_card.append(list_of_url[s])
    s += 2

len(only_score_card)

# getting only scorecard urls

89

44

In [45]:
# removing last 2 elements from list as it is not scorecard
k = 2
a= only_score_card[: len(only_score_card) - k]
len(a)

42

In [46]:
final_list = a

In [101]:
(final_list)

['https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/namibia-vs-sri-lanka-1st-match-first-round-group-a-1298135/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/netherlands-vs-united-arab-emirates-2nd-match-first-round-group-a-1298136/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/scotland-vs-west-indies-3rd-match-first-round-group-b-1298137/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/ireland-vs-zimbabwe-4th-match-first-round-group-b-1298138/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/namibia-vs-netherlands-5th-match-first-round-group-a-1298139/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/sri-lanka-vs-united-arab-emirates-6th-match-first-round-group-a-1298140/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/ireland-vs-scotland-7th-match-first-round-group-b-1298141/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/west-indies-vs-zimbabwe-8th-match-first-round-group-b-1298142/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/netherlands-vs-sri-lanka-9th-match-first-round-group-a-1298143/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/namibia-vs-united-arab-emirates-10th-match-first-round-group-a-1298144/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/ireland-vs-west-indies-11th-match-first-round-group-b-1298145/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/scotland-vs-zimbabwe-12th-match-first-round-group-b-1298146/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/australia-vs-new-zealand-13th-match-group-1-1298147/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/afghanistan-vs-england-14th-match-group-1-1298148/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/ireland-vs-sri-lanka-15th-match-group-1-1298149/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/india-vs-pakistan-16th-match-group-2-1298150/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/bangladesh-vs-netherlands-17th-match-group-2-1298151/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/south-africa-vs-zimbabwe-18th-match-group-2-1298152/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/australia-vs-sri-lanka-19th-match-group-1-1298153/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/england-vs-ireland-20th-match-group-1-1298154/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/bangladesh-vs-south-africa-22nd-match-group-2-1298156/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/india-vs-netherlands-23rd-match-group-2-1298157/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/pakistan-vs-zimbabwe-24th-match-group-2-1298158/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/new-zealand-vs-sri-lanka-27th-match-group-1-1298161/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/bangladesh-vs-zimbabwe-28th-match-group-2-1298162/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/netherlands-vs-pakistan-29th-match-group-2-1298163/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/india-vs-south-africa-30th-match-group-2-1298164/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/australia-vs-ireland-31st-match-group-1-1298165/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/afghanistan-vs-sri-lanka-32nd-match-group-1-1298166/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/england-vs-new-zealand-33rd-match-group-1-1298167/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/netherlands-vs-zimbabwe-34th-match-group-2-1298168/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/bangladesh-vs-india-35th-match-group-2-1298169/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/pakistan-vs-south-africa-36th-match-group-2-1298170/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/ireland-vs-new-zealand-37th-match-group-1-1298171/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/australia-vs-afghanistan-38th-match-group-1-1298172/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/england-vs-sri-lanka-39th-match-group-1-1298173/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/netherlands-vs-south-africa-40th-match-group-2-1298174/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/bangladesh-vs-pakistan-41st-match-group-2-1298175/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/india-vs-zimbabwe-42nd-match-group-2-1298176/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/new-zealand-vs-pakistan-1st-semi-final-1298177/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/england-vs-india-2nd-semi-final-1298178/full-scorecard',
 'https://www.espncricinfo.com//series/icc-men-s-t20-world-cup-2022-23-1298134/england-vs-pakistan-final-1298179/full-scorecard']

In [67]:
sw = f_url.find_all("thead")[0].text
sw
# for x in sw:
#     print(x, end=" ")

'BATTING\xa0RBM4s6sSR'

In [70]:
sw = f_url.find_all("table")[0].text
with open("info.txt", 'w') as f:
    write = csv.writer(f)
    write.writerows(sw)

In [117]:

con = []
for link in final_list:
    d = pd.read_html(link)
    df_batting = pd.concat([d[0], d[2]])
    con.append(df_batting)

con[0]
# type(d[0])

,BATTING,Unnamed: 1,R,B,M,4s,6s,SR,Unnamed: 8,Unnamed: 9
0,Michael van Lingen,c Pramod Madushan b Chameera,3,6,7,0,0,50.00,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,15,1,0,100.00,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,18,1,2,166.66,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,49,2,0,108.33,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Gerhard Erasmus (c),c Gunathilaka b PWH de Silva,20,24,30,0,0,83.33,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,44,4,0,157.14,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,David Wiese,c †Mendis b Theekshana,0,1,4,0,0,0.00,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,JJ Smit,not out,31,16,29,2,2,193.75,NaN,NaN
15,Extras,"(b 1, w 9)",10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,TOTAL,20 Ov (RR: 8.15),163/7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...","Did not bat: Zane Green †, Bernard Scholtz, Be...",NaN
18,"Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...","Fall of wickets: 1-6 (Michael van Lingen, 1.2 ...",NaN
0,Pathum Nissanka,c Smit b Shikongo,9,10,16,1,0,90.00,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kusal Mendis †,c †Green b Wiese,6,6,8,0,0,100.00,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,25,1,0,109.09,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Danushka Gunathilaka,c †Green b Shikongo,0,1,2,0,0,0.00,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,39,2,0,95.23,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Dasun Shanaka (c),c †Green b Frylinck,29,23,37,2,1,126.08,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Wanindu Hasaranga,c Loftie-Eaton b Scholtz,4,8,9,0,0,50.00,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Chamika Karunaratne,c Baard b Smit,5,8,15,0,0,62.50,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Pramod Madushan,run out (van Lingen/†Green),0,0,4,0,0,-,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Dushmantha Chameera,c Erasmus b Wiese,8,15,20,0,0,53.33,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Maheesh Theekshana,not out,11,11,14,0,1,100.00,NaN,NaN
21,Extras,"(lb 2, w 2)",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,TOTAL,19 Ov (RR: 5.68),108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...","Fall of wickets: 1-12 (Kusal Mendis, 1.4 ov), ...",NaN

In [118]:
# a = 0
# for i in range(0, len(con), 2):
#     pd.concat(con[[i], con[a+1]])
#     a = a + 2

len(con)

42

In [84]:
# import webbrowser
# webbrowser.open(final_score_card)

True